### ISSUE TITLE
Relax peer dependencies

### ISSUE THREAD

**Issue by axelboc** [pmndrs/use-asset#3]
![image](https://user-images.githubusercontent.com/2936402/97865587-bba58f00-1d0a-11eb-8b9d-dab54a03f685.png)

Does it need to have `react-three-fiber` and `three` as peer dependencies at all? It seems pretty generic, but perhaps I'm missing something.

**Comment by axelboc** [comment]
For React, I would recommend using `>=16.13`.

**Comment by drcmda** [comment]
oh, no, you're right. this is because i copied the project files. would you want to make a pr? im on the move right now.
