### ISSUE TITLE
Increase fetching threshold for infinite load on scroll example

### ISSUE THREAD

**Issue by Doesntmeananything** [pmndrs/use-asset#7]
I'm looking into using `react-three-fiber` and `use-asset` for one of my projects, and I've noticed that the [infinite load example](https://codesandbox.io/s/use-asset-forked-ouzkc?file=/src/App.js) doesn't work on my display. Looking into the code, this condition for triggering fetching may never be true for larger screens:

```javascript
e.target.scrollTop > content.current.scrollHeight - 1000
```
It's a very minor thing, but I was wondering if it makes sense to increase this threshold and make it independent of the screen size, e.g. something like:

```javascript
e.target.scrollTop > content.current.scrollHeight / 2
```

And thanks very much for all the awesome work on the poimandres familiy of libraries! I really appreciate how you use the most interesting features of React to make sure that all the different use cases stay performant and simple to use. :+1:

**Comment by drcmda** [comment]
these demos are very basic. i guess the idea was that if scrolltop is at the end of content minus a buffer it should start fetching new items. yours would trigger all the time if the scrollbar has reached half the content height.

should be more along the lines of e.target.scrollTop > content.current.scrollHeight - document.body.clientHeight but doesn't matter so much, people will find their own solutions.

**Comment by Doesntmeananything** [comment]
Ok, gotcha! Doesn't really make sense to keep this one open then. Thanks.
